### ISSUE TITLE
Guides and API Documentation

### ISSUE THREAD

**Issue by ianlivingstone** [mortendahl/tf-encrypted#123]
### Background

Today, we have a few examples that we've put together along with a short getting started guide. It's great for the stage of the project.

However, as we build towards a beta or more stable release we'll need to expand upon these guides and properly document the API.

This issue is a discussion for the type of documentation we require, where it should live, and the targeted audience.

### TODO

- [x] Establish the structure and process for deploying documentation (via readthedocs.org.)
- [x] Update README with link to docs and other getting started components
- [x] Write a getting started guide that uses google colab (public training, private prediction, and loading a pretrained model)
- [x] Update tf-encrypted on PyPI so we can get access to the latest API in Google Colab.
- [x] Write a overview of our technology (can link off to blog post or paper) with architecture diagram
- [ ] Add link to paper to the README and Docs Landing Page
- Flush out the API documentation with examples, function signature, and other information.
  - [ ] session
  - [ ] config
  - [ ] define_pub/private_variable
  - [ ] pondtensors
  - protocols
     - [ ] pond
     - [ ] secureNN
  - [ ] input
  - [ ] output

**Comment by ianlivingstone** [comment]
I setup time for the dropoutlabs team to discuss this issue.

**Comment by bendecoste** [comment]
I took some time to play around with how writing and using readthedocs would actually work.  I think this is a good option going forward.  The highlights are

- We can use inline docs, but you need to manually link to them (more on this below)
- It is easy to write guides and have API docs in the same place
- Markdown is supported (though they use `.rst` by default, which is similar but more powerful)

~~~~~

> We can use inline docs, but you need to manually link to them (more on this below)

Re inline docs.  As far as I can tell you do indeed need to manually link to your inline documentation, but you can do this on a module level, so in general it is more or less automatic.  For example, 

```
.. automodule:: tensorflow_encrypted.protocol
  :members:
```

will generate all of the docs that we have written for .protocol

![image](https://user-images.githubusercontent.com/1411145/46676859-c0dd9180-cbb7-11e8-931d-77c68f8825c4.png)

> It is easy to write guides and have API docs in the same place

Again quite easy, you can make entire pages devoted to API as done above, it is also easy to intertwine or write a page that is just a guide

> Markdown is supported (though they use `.rst` by default, which is similar but more powerful)

Here is a simple example

![image](https://user-images.githubusercontent.com/1411145/46676937-f3878a00-cbb7-11e8-9d79-f77107b20b20.png)

renders

![image](https://user-images.githubusercontent.com/1411145/46676957-fd10f200-cbb7-11e8-8c32-803ad6bd905b.png)

**Comment by bendecoste** [comment]
Okay need some feedback from everyone:

Obviously we like type annotations but they are ugly as sin when rendered in the docs. For reference, here is the constructor for `Pond`:

```python
def __init__(
            self,
            server_0: Optional[Player] = None,
            server_1: Optional[Player] = None,
            crypto_producer: Optional[Player] = None,
            use_noninteractive_truncation: bool = False,
            tensor_factory: AbstractFactory = Int100Factory(),
            verify_precision: bool=True) -> None:
```

This is nice and it lets us see what the types it takes are, which is nice.  However, when this is rendered, it comes out looking like this:

![image](https://user-images.githubusercontent.com/1411145/46692161-f2b51f00-cbdc-11e8-887c-4aa60ab00d29.png)

I find this impossible to read.  I see there being 3 options here

### use quotes rather than the actual type.  You can (and sometimes have to) annotate stuff like this:

```python
def __init__(
            self,
            server_0: Optional['Player'] = None,
            server_1: Optional['Player'] = None,
            crypto_producer: Optional['Player'] = None,
            use_noninteractive_truncation: bool = False,
            tensor_factory: AbstractFactory = Int100Factory(),
            verify_precision: bool=True) -> None:
```

(note the quotes around `Player`), this changes the rendering to this:

![image](https://user-images.githubusercontent.com/1411145/46692266-39a31480-cbdd-11e8-92cf-17c263744e24.png)

This is a little bit better but not much, it also doens't fix the same issue we have with `Int100Factory`.

The more nuclear option would be to stop using type annotations and rely on public documentation to tell us what the type is.

Consider this old definition for `bitwise_and` in `secureNN`:

```python
    @memoize
    def bitwise_and(self, x: PondTensor, y: PondTensor) -> PondTensor:
        """
        Computes bitwise `AND` of the input
        """
        assert not x.is_scaled, "Input is not supposed to be scaled"
        assert not y.is_scaled, "Input is not supposed to be scaled"
        with tf.name_scope('bitwise_and'):
            return x * y
```

This will render like this:
![image](https://user-images.githubusercontent.com/1411145/46692441-a7e7d700-cbdd-11e8-9484-2c73691dbd71.png)


This could alternatively be written like so

```python
@memoize
    def bitwise_and(self, x, y):
        """
        Computes the bitwise `AND` of the given inputs.
            `(x * y)`

        :param x: a :class:`~tensorflow_encrypted.protocol.pond.PondTensor`
        :param y: a :class:`~tensorflow_encrypted.protocol.pond.PondTensor`
        :rtype: a :class:`~tensorflow_encrypted.protocol.pond.PondTensor`
        """
        assert not x.is_scaled, "Input is not supposed to be scaled"
        assert not y.is_scaled, "Input is not supposed to be scaled"
        return x * y
```

Which will render like this

![image](https://user-images.githubusercontent.com/1411145/46692498-d36ac180-cbdd-11e8-9561-b96f0c687eba.png)

Notice that `PondTensor` is now clickable:

![image](https://user-images.githubusercontent.com/1411145/46692521-e4b3ce00-cbdd-11e8-98e5-0f657676a1cb.png)


(above photo still ugly)


You can also do a hybrid of the two (e.g. always use strings)

```python
    def bitwise_and(self, x: 'PondTensor', y: 'PondTensor') -> 'PondTensor':
```

renders

![image](https://user-images.githubusercontent.com/1411145/46692599-1dec3e00-cbde-11e8-9f92-0cfc657523cd.png)

Note however the names in the function sig are not clickable and this makes the definition say PondTensor a lot

**Comment by bendecoste** [comment]
- session
- config
- define_pub/private_variable
- pondtensors
- protocols
  - pond
  - secureNN
- guides (adapted from elsewhere in the repo)
- input
- output
- architecture diagram / overview

**Comment by yanndupis** [comment]
Also quick note, to get access to the latest API and protocols etc. in Google Colab we will have to update tf-encrypted on PyPI. I have added this to the list above.

**Comment by ianlivingstone** [comment]
>  Update tf-encrypted on PyPI so we can get access to the latest API in Google Colab.

I'll do a release of tf-encrypted either tonight or tomorrow morning once #211 lands in master.

**Comment by bendecoste** [comment]
Unresolved --

- What is the inputter_fn on define input functions in pond?
