### ISSUE TITLE
Implement 1-D Convolutions

### ISSUE THREAD

**Issue by ianlivingstone** [mortendahl/tf-encrypted#200]
We'd like to implement 1-D Convolutions and then use them to evaluate and benchmark our support for sequence-based models (e.g. text classification with bag of 1d-convolutions, etc.).

Depends on #358

**Comment by ianlivingstone** [comment]
@jvmancuso could you add some more colour to this issue? :)

**Comment by jvmancuso** [comment]
## Plan
- [ ] Implement missing ops with necessary conversion logic (below)
- [ ] Audit and tweak Conv2d, as needed (we're not 100% confident that the original conv2d layer was implemented to handle non-standard input tensors)
- [ ] Debug and test character-level language model conversion into TFE

### Missing Ops:
- [ ] [`tf.pad`](https://www.tensorflow.org/api_docs/python/tf/pad)
- [ ] [`tf.required_space_to_batch_paddings`](https://www.tensorflow.org/api_docs/python/tf/required_space_to_batch_paddings)
- [ ] [`tf.stack`](https://www.tensorflow.org/api_docs/python/tf/stack) (previously known as `tf.pack`, still shows up in protobuf as a `Pack` op
- [ ] [`tf.concat`](https://www.tensorflow.org/api_docs/python/tf/concat)
- [ ] [`tf.batch_to_space_nd`](https://www.tensorflow.org/api_docs/python/tf/batch_to_space_nd)
- [ ] [`tf.space_to_batch_nd`](https://www.tensorflow.org/api_docs/python/tf/space_to_batch_nd)

**Comment by kamathhrishi** [comment]
Could you elaborate more on what non standard input tensors could be like ?

**Comment by jvmancuso** [comment]
Standard for Conv2D would likely be something like an input of shape (n, d, h, w) where usually h=w, but with Conv1D, the inputs to Conv2d are reshaped to (n, d, h, 1) or something similar. We'll just want to make sure our current Conv2d can support this shape of input.

Once #297 is merged we'll be able to convert a Conv1D layer into tf-encrypted, but if our Conv2D implementation can't handle that input shape, we'll probably run into a few errors when we try.  Note we'll likely have a PR for #297 in progress by end of day or early tomorrow
