### ISSUE TITLE
Secure Random

### ISSUE THREAD

**Issue by justin1121** [mortendahl/tf-encrypted#273]
This is an epic to track the rest of the work that needs to be done to ship a good secure random implementation.

The original [PR](https://github.com/mortendahl/tf-encrypted/pull/265) should be merged soon.

The other issues apart of this epic:

- [x] circleci builds for different platforms: https://github.com/mortendahl/tf-encrypted/issues/271
- [x] ship different versions of tf custom op shared object for each tf version we want to support
- [x] other secure random helper functions (no seed, generate seed, etc): https://github.com/mortendahl/tf-encrypted/issues/274

**Comment by ianlivingstone** [comment]
From @mortendahl: Can we verify if this function works for signed integers (e.g. adding a test)?

**Comment by justin1121** [comment]
Done!

**Comment by justin1121** [comment]
Pulling out https://github.com/mortendahl/tf-encrypted/issues/137 and https://github.com/mortendahl/tf-encrypted/issues/270, they can be treated as longer running issues. This can be closed once https://github.com/mortendahl/tf-encrypted/issues/274 is closed.
